name: synbio
channels:
  - defaults
dependencies:
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jupyter=1.0.0
  - jupyterlab=3.4.4
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - notebook=6.4.12
  - numpy=1.23.1
  - numpy-base
  - pip
  - python
  - scipy=1.9.1
